

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const CLON_CART = 'CLON_CART'



// add key to async story.
export const KEYTOKEN = 'KEYTOKEN'
// user lOGIN IN....>

export const ADD_USER_LOADING = 'ADD_USER_LOADING'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_EMPTY = 'ADD_USER_EMPTY'



// GET ALL PRODUCTS.. 
export const ADD_PRODUCT_LOADING = 'ADD_PRODUCTT_LOADING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'


// GET category.. 
export const ADD_CATEGORY_LOADING = 'ADD_CATEGORU_LOADING'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL'



// CREATE PRODUCT..
export const ADD_PRODUCT_CREATE_LOADING = 'ADD_PRODUCT_CREATE_LOADING'
export const ADD_PRODUCT_CREATE_SUCCESS = 'ADD_PRODUCT_CREATE_SUCCESS'
export const ADD_PRODUCT_CREATE_FAIL = 'ADD_PRODUCT_CREATE_FAIL'



// delete product.. 
export const ADD_PRODUCT_DELETE_LOADING = 'ADD_PRODUCT_DELETE_LOADING'
export const ADD_PRODUCT_DELETE_SUCCESS = 'ADD_PRODUCT_DELETE_SUCCESS'
export const ADD_PRODUCT_DELETE_FAIL = 'ADD_PRODUCT_DELETE_FAIL'


// CREATE CATEGORY..
export const ADD_CREATE_CATEGORY_LOADING = 'ADD_CREATE_CATEGORY_LOADING'
export const ADD_CREATE_CATEGORY_SUCCESS = 'ADD_CREATE_CATEGORY_SUCCESS'
export const ADD_CREATE_CATEGORY_FAIL = 'ADD_CREATE_CATEGORY_FAIL'




// update product.. 
export const ADD_PRODUCT_UPDATE_LOADING = 'ADD_PRODUCT_UPDATE_LOADING'
export const ADD_PRODUCT_UPDATE_SUCCESS = 'ADD_PRODUCT_UPDATE_SUCCESS'
export const ADD_PRODUCT_UPDATE_FAIL = 'ADD_PRODUCT_UPDATE_FAIL'




export const ADD_NEXT_LOADING = 'ADD_NEXT_LOADING'
export const ADD_PAGINYION_SUCCESS = 'ADD_PAGINYION_SUCCESS'
export const ADD_NEXT_PAGE = 'ADD_NEXT_PAGE'
export const ADD_PAGINYION_FAIL = 'ADD_PAGINYION_FAIL'




// create category product... filter
export const ADD_CATEGORY_FILTER_LOADING = 'ADD_CATEGORY_FILTER_LOADING'
export const ADD_CATEGORY_APPEND_LOADING = 'ADD_CATEGORY_APPEND_LOADING'
export const ADD_CATEGORY_NEXTPAGE_LOADING = 'ADD_CATEGORY_NEXTPAGE_LOADING'
export const ADD_CATEGORY_NEXTPAGE_FAIL = 'ADD_CATEGORY_NEXTPAGE_FAIL'





// append category and product toga
export const ADD_CATEGORYPRODUCT_APPEND = 'ADD_CATEGORYPRODUCT_APPEND'
export const ADD_ADDNUMBERCATEGORYPRODUCT = 'ADD_ADDNUMBERCATEGORYPRODUCT'
export const ADD_CATEGORYPRODUCT_FAIL = 'ADD_CATEGORYPRODUCT_FAIL'





// add like to my story... 
export const ADD_LIKE_CART_SUCCESS = 'ADD_LIKE_CART_SUCCESS'
export const STORY_LINE_ITEM = 'STORY_LINE_ITEM'

// story like..
export const ADD_DATA = 'ADD_DATA'
export const REMOVE_ITEM_STORY = 'REMOVE_ITEM_STORY'






// ............................... start product id ................................./
export const PRODUCT_ID_LOADING = 'PRODUCT_ID_LOADING'
export const PRODUCT_ID_SUCCESS = 'PRODUCT_ID_SUCCESS'
export const PRODUCT_ID_FAIL = 'PRODUCT_ID_FAIL'
// ............................... end product id ................................./